// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: shibafu528/utissue/checkins.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CheckinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckedInAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=checked_in_at,json=checkedInAt,proto3" json:"checked_in_at,omitempty"`
	Note        string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	Link        string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Tags        []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *CheckinRequest) Reset() {
	*x = CheckinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shibafu528_utissue_checkins_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinRequest) ProtoMessage() {}

func (x *CheckinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shibafu528_utissue_checkins_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckinRequest.ProtoReflect.Descriptor instead.
func (*CheckinRequest) Descriptor() ([]byte, []int) {
	return file_shibafu528_utissue_checkins_proto_rawDescGZIP(), []int{0}
}

func (x *CheckinRequest) GetCheckedInAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedInAt
	}
	return nil
}

func (x *CheckinRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CheckinRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *CheckinRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CheckinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Checkin *Checkin `protobuf:"bytes,1,opt,name=checkin,proto3" json:"checkin,omitempty"`
}

func (x *CheckinResponse) Reset() {
	*x = CheckinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shibafu528_utissue_checkins_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinResponse) ProtoMessage() {}

func (x *CheckinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shibafu528_utissue_checkins_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckinResponse.ProtoReflect.Descriptor instead.
func (*CheckinResponse) Descriptor() ([]byte, []int) {
	return file_shibafu528_utissue_checkins_proto_rawDescGZIP(), []int{1}
}

func (x *CheckinResponse) GetCheckin() *Checkin {
	if x != nil {
		return x.Checkin
	}
	return nil
}

var File_shibafu528_utissue_checkins_proto protoreflect.FileDescriptor

var file_shibafu528_utissue_checkins_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x68, 0x69, 0x62, 0x61, 0x66, 0x75, 0x35, 0x32, 0x38, 0x2f, 0x75, 0x74, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x73, 0x68, 0x69, 0x62, 0x61, 0x66, 0x75, 0x35, 0x32, 0x38, 0x2e,
	0x75, 0x74, 0x69, 0x73, 0x73, 0x75, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x73, 0x68, 0x69, 0x62, 0x61, 0x66,
	0x75, 0x35, 0x32, 0x38, 0x2f, 0x75, 0x74, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2f, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x0e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a,
	0x0d, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x5f, 0x61, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0b, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x49, 0x6e, 0x41, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x48, 0x0a, 0x0f, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x07,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x73, 0x68, 0x69, 0x62, 0x61, 0x66, 0x75, 0x35, 0x32, 0x38, 0x2e, 0x75, 0x74, 0x69, 0x73, 0x73,
	0x75, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x07, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x69, 0x6e, 0x32, 0x5d, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x73, 0x12,
	0x51, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x22, 0x2e, 0x73, 0x68, 0x69, 0x62,
	0x61, 0x66, 0x75, 0x35, 0x32, 0x38, 0x2e, 0x75, 0x74, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x73, 0x68, 0x69, 0x62, 0x61, 0x66, 0x75, 0x35, 0x32, 0x38, 0x2e, 0x75, 0x74, 0x69, 0x73, 0x73,
	0x75, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x68, 0x69, 0x62, 0x61, 0x66, 0x75, 0x35, 0x32, 0x38, 0x2f, 0x75, 0x74, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shibafu528_utissue_checkins_proto_rawDescOnce sync.Once
	file_shibafu528_utissue_checkins_proto_rawDescData = file_shibafu528_utissue_checkins_proto_rawDesc
)

func file_shibafu528_utissue_checkins_proto_rawDescGZIP() []byte {
	file_shibafu528_utissue_checkins_proto_rawDescOnce.Do(func() {
		file_shibafu528_utissue_checkins_proto_rawDescData = protoimpl.X.CompressGZIP(file_shibafu528_utissue_checkins_proto_rawDescData)
	})
	return file_shibafu528_utissue_checkins_proto_rawDescData
}

var file_shibafu528_utissue_checkins_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shibafu528_utissue_checkins_proto_goTypes = []interface{}{
	(*CheckinRequest)(nil),        // 0: shibafu528.utissue.CheckinRequest
	(*CheckinResponse)(nil),       // 1: shibafu528.utissue.CheckinResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*Checkin)(nil),               // 3: shibafu528.utissue.Checkin
}
var file_shibafu528_utissue_checkins_proto_depIdxs = []int32{
	2, // 0: shibafu528.utissue.CheckinRequest.checked_in_at:type_name -> google.protobuf.Timestamp
	3, // 1: shibafu528.utissue.CheckinResponse.checkin:type_name -> shibafu528.utissue.Checkin
	0, // 2: shibafu528.utissue.Checkins.Create:input_type -> shibafu528.utissue.CheckinRequest
	1, // 3: shibafu528.utissue.Checkins.Create:output_type -> shibafu528.utissue.CheckinResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shibafu528_utissue_checkins_proto_init() }
func file_shibafu528_utissue_checkins_proto_init() {
	if File_shibafu528_utissue_checkins_proto != nil {
		return
	}
	file_shibafu528_utissue_checkin_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_shibafu528_utissue_checkins_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shibafu528_utissue_checkins_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shibafu528_utissue_checkins_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shibafu528_utissue_checkins_proto_goTypes,
		DependencyIndexes: file_shibafu528_utissue_checkins_proto_depIdxs,
		MessageInfos:      file_shibafu528_utissue_checkins_proto_msgTypes,
	}.Build()
	File_shibafu528_utissue_checkins_proto = out.File
	file_shibafu528_utissue_checkins_proto_rawDesc = nil
	file_shibafu528_utissue_checkins_proto_goTypes = nil
	file_shibafu528_utissue_checkins_proto_depIdxs = nil
}
