// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: shibafu528/utissue/checkins.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateCheckinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckedInAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=checked_in_at,json=checkedInAt,proto3" json:"checked_in_at,omitempty"`
	Note        string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	Link        string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Tags        []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *CreateCheckinRequest) Reset() {
	*x = CreateCheckinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shibafu528_utissue_checkins_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCheckinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckinRequest) ProtoMessage() {}

func (x *CreateCheckinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shibafu528_utissue_checkins_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckinRequest.ProtoReflect.Descriptor instead.
func (*CreateCheckinRequest) Descriptor() ([]byte, []int) {
	return file_shibafu528_utissue_checkins_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCheckinRequest) GetCheckedInAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedInAt
	}
	return nil
}

func (x *CreateCheckinRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CreateCheckinRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *CreateCheckinRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateCheckinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Checkin *Checkin `protobuf:"bytes,1,opt,name=checkin,proto3" json:"checkin,omitempty"`
}

func (x *CreateCheckinResponse) Reset() {
	*x = CreateCheckinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shibafu528_utissue_checkins_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCheckinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckinResponse) ProtoMessage() {}

func (x *CreateCheckinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shibafu528_utissue_checkins_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckinResponse.ProtoReflect.Descriptor instead.
func (*CreateCheckinResponse) Descriptor() ([]byte, []int) {
	return file_shibafu528_utissue_checkins_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCheckinResponse) GetCheckin() *Checkin {
	if x != nil {
		return x.Checkin
	}
	return nil
}

type GetCheckinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCheckinRequest) Reset() {
	*x = GetCheckinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shibafu528_utissue_checkins_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCheckinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckinRequest) ProtoMessage() {}

func (x *GetCheckinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shibafu528_utissue_checkins_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckinRequest.ProtoReflect.Descriptor instead.
func (*GetCheckinRequest) Descriptor() ([]byte, []int) {
	return file_shibafu528_utissue_checkins_proto_rawDescGZIP(), []int{2}
}

func (x *GetCheckinRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCheckinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Checkin *Checkin `protobuf:"bytes,1,opt,name=checkin,proto3" json:"checkin,omitempty"`
}

func (x *GetCheckinResponse) Reset() {
	*x = GetCheckinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shibafu528_utissue_checkins_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCheckinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckinResponse) ProtoMessage() {}

func (x *GetCheckinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shibafu528_utissue_checkins_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckinResponse.ProtoReflect.Descriptor instead.
func (*GetCheckinResponse) Descriptor() ([]byte, []int) {
	return file_shibafu528_utissue_checkins_proto_rawDescGZIP(), []int{3}
}

func (x *GetCheckinResponse) GetCheckin() *Checkin {
	if x != nil {
		return x.Checkin
	}
	return nil
}

var File_shibafu528_utissue_checkins_proto protoreflect.FileDescriptor

var file_shibafu528_utissue_checkins_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x68, 0x69, 0x62, 0x61, 0x66, 0x75, 0x35, 0x32, 0x38, 0x2f, 0x75, 0x74, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x73, 0x68, 0x69, 0x62, 0x61, 0x66, 0x75, 0x35, 0x32, 0x38, 0x2e,
	0x75, 0x74, 0x69, 0x73, 0x73, 0x75, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x73, 0x68, 0x69, 0x62, 0x61, 0x66,
	0x75, 0x35, 0x32, 0x38, 0x2f, 0x75, 0x74, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2f, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x01, 0x0a, 0x14, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0d, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x69,
	0x6e, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x49,
	0x6e, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22,
	0x4e, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x68, 0x69, 0x62,
	0x61, 0x66, 0x75, 0x35, 0x32, 0x38, 0x2e, 0x75, 0x74, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x22,
	0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x4b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x68,
	0x69, 0x62, 0x61, 0x66, 0x75, 0x35, 0x32, 0x38, 0x2e, 0x75, 0x74, 0x69, 0x73, 0x73, 0x75, 0x65,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69,
	0x6e, 0x32, 0xbf, 0x01, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x73, 0x12, 0x5d,
	0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x28, 0x2e, 0x73, 0x68, 0x69, 0x62, 0x61,
	0x66, 0x75, 0x35, 0x32, 0x38, 0x2e, 0x75, 0x74, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x2e, 0x73, 0x68, 0x69, 0x62, 0x61, 0x66, 0x75, 0x35, 0x32, 0x38, 0x2e,
	0x75, 0x74, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a,
	0x03, 0x47, 0x65, 0x74, 0x12, 0x25, 0x2e, 0x73, 0x68, 0x69, 0x62, 0x61, 0x66, 0x75, 0x35, 0x32,
	0x38, 0x2e, 0x75, 0x74, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x68,
	0x69, 0x62, 0x61, 0x66, 0x75, 0x35, 0x32, 0x38, 0x2e, 0x75, 0x74, 0x69, 0x73, 0x73, 0x75, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x68, 0x69, 0x62, 0x61, 0x66, 0x75, 0x35, 0x32, 0x38, 0x2f, 0x75, 0x74, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shibafu528_utissue_checkins_proto_rawDescOnce sync.Once
	file_shibafu528_utissue_checkins_proto_rawDescData = file_shibafu528_utissue_checkins_proto_rawDesc
)

func file_shibafu528_utissue_checkins_proto_rawDescGZIP() []byte {
	file_shibafu528_utissue_checkins_proto_rawDescOnce.Do(func() {
		file_shibafu528_utissue_checkins_proto_rawDescData = protoimpl.X.CompressGZIP(file_shibafu528_utissue_checkins_proto_rawDescData)
	})
	return file_shibafu528_utissue_checkins_proto_rawDescData
}

var file_shibafu528_utissue_checkins_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shibafu528_utissue_checkins_proto_goTypes = []interface{}{
	(*CreateCheckinRequest)(nil),  // 0: shibafu528.utissue.CreateCheckinRequest
	(*CreateCheckinResponse)(nil), // 1: shibafu528.utissue.CreateCheckinResponse
	(*GetCheckinRequest)(nil),     // 2: shibafu528.utissue.GetCheckinRequest
	(*GetCheckinResponse)(nil),    // 3: shibafu528.utissue.GetCheckinResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*Checkin)(nil),               // 5: shibafu528.utissue.Checkin
}
var file_shibafu528_utissue_checkins_proto_depIdxs = []int32{
	4, // 0: shibafu528.utissue.CreateCheckinRequest.checked_in_at:type_name -> google.protobuf.Timestamp
	5, // 1: shibafu528.utissue.CreateCheckinResponse.checkin:type_name -> shibafu528.utissue.Checkin
	5, // 2: shibafu528.utissue.GetCheckinResponse.checkin:type_name -> shibafu528.utissue.Checkin
	0, // 3: shibafu528.utissue.Checkins.Create:input_type -> shibafu528.utissue.CreateCheckinRequest
	2, // 4: shibafu528.utissue.Checkins.Get:input_type -> shibafu528.utissue.GetCheckinRequest
	1, // 5: shibafu528.utissue.Checkins.Create:output_type -> shibafu528.utissue.CreateCheckinResponse
	3, // 6: shibafu528.utissue.Checkins.Get:output_type -> shibafu528.utissue.GetCheckinResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_shibafu528_utissue_checkins_proto_init() }
func file_shibafu528_utissue_checkins_proto_init() {
	if File_shibafu528_utissue_checkins_proto != nil {
		return
	}
	file_shibafu528_utissue_checkin_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_shibafu528_utissue_checkins_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCheckinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shibafu528_utissue_checkins_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCheckinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shibafu528_utissue_checkins_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCheckinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shibafu528_utissue_checkins_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCheckinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shibafu528_utissue_checkins_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shibafu528_utissue_checkins_proto_goTypes,
		DependencyIndexes: file_shibafu528_utissue_checkins_proto_depIdxs,
		MessageInfos:      file_shibafu528_utissue_checkins_proto_msgTypes,
	}.Build()
	File_shibafu528_utissue_checkins_proto = out.File
	file_shibafu528_utissue_checkins_proto_rawDesc = nil
	file_shibafu528_utissue_checkins_proto_goTypes = nil
	file_shibafu528_utissue_checkins_proto_depIdxs = nil
}
